# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'THG' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'Firebase'
	pod 'Firebase/Messaging'
  # Pods for THG



  target 'THGTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'THG-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for THG-tvOS

  target 'THG-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
