# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'THG' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'Firebase'
	pod 'Firebase/Messaging'
  # Pods for THG



  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

  target 'THGTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'THG-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for THG-tvOS

  target 'THG-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
